services:
  - type: web
    name: diabetes-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9 